version: "3.8"

services: 

    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.12.1
        container_name: elasticsearch1
        environment:
            - node.name=es01
            - discovery.type=single-node
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        ulimits:
            memlock:
                soft: -1
                hard: -1
        ports:
            - 9200:9200

    logstash:
        build: 
            context: ./logstash
            dockerfile: Dockerfile
        image: 127.0.0.1/logstash
        depends_on: 
            - elasticsearch

    nginx-server:
        build: 
            context: ./nginx
            dockerfile: Dockerfile
        image: 127.0.0.1/nginx-server
        depends_on: 
            - logstash
        ports: 
            - 8081:80
    
    # Your Code Goes Here
    api-server:
        build:
            context: .
            dockerfile: Dockerfile
        image: 127.0.0.1/api-server

    kibana-dashboard:
        image: docker.elastic.co/kibana/kibana:7.12.1
        environment: 
            - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
        ports: 
            - 5601:5601